[project]
name = 'binconvfm'
version = '1.0.0'
requires-python = '>=3.11'
dependencies = [
    'lightning>=2.5.2',
    'matplotlib>=3.10.3',
    'notebook>=7.4.4',
    'ipywidgets>=8.1.7',
]

[tool.setuptools]
packages = ['binconvfm']